// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oejljvdpdmcabferfcqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lamxqdmRwZG1jYWJmZXJmY3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI0NjcsImV4cCI6MjA2OTI4ODQ2N30.b3Qe0Gn39YAmAqKcaHVwOYSseUsC3IYTIBayuOi6akI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});